### ISSUE TITLE
Something is error when I run torchlens on my pc

### ISSUE THREAD

**Issue by whisperLiang** [johnmarktaylor91/torchlens#23]
D:\Application\miniconda\envs\coinfer\lib\site-packages\torch\overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
D:\Application\miniconda\envs\coinfer\lib\site-packages\torch\overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
D:\Application\miniconda\envs\coinfer\lib\site-packages\torch\overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
D:\Application\miniconda\envs\coinfer\lib\site-packages\torch\overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
Traceback (most recent call last):
  File "d:\ProgramCode\torchlens\debug_torchlens.py", line 10, in <module>
    model_history = tl.log_forward_pass(model, x, vis_opt='unrolled')
  File "d:\ProgramCode\torchlens\torchlens\user_funcs.py", line 144, in log_forward_pass
    model_history.render_graph(
TypeError: ModelHistory.render_graph() takes from 1 to 8 positional arguments but 14 were given
![微信截图_20240801220554](https://github.com/user-attachments/assets/6510b1fd-88da-4a38-9b28-2128e4e8d270)

**Comment by johnmarktaylor91** [comment]
Hmm, it's working for me on the latest pip release. If you pip uninstall torchlens and then reinstall, do you still get the same error?

**Comment by johnmarktaylor91** [comment]
Awesome, glad it's working well for you :) Closing if no more issues, but feel free to reopen if more problems arise.

**Comment by johnmarktaylor91** [comment]
By submodel, do you mean a module inside the model that itself contains multiple operations?  You can fetch the layer corresponding to an output of such a module by simply using the “address” of the module. For example, to get the output of the `features` block in AlexNet you would do `model_history[‘features’]`. You can easily see the addresses of all the modules using the visualization, or by inspecting the model’s code.

**Comment by johnmarktaylor91** [comment]
If I understand your question, yes you can do this in PyTorch, for example:

`submodel = AlexNet.features `

Then you can treat this submodule as its own model, including fetching the parameters or passing to TorchLens. Was that what you wanted to know?

**Comment by johnmarktaylor91** [comment]
Like this?

`import torch
import torchlens as tl
import torchvision

model = torchvision.models.alexnet()
submodule = model.classifier
x = torch.rand(6, 9216)
print(list(submodule.parameters()))
model_history = tl.log_forward_pass(submodule, x, vis_opt='unrolled')`

<img width="218" alt="image" src="https://github.com/user-attachments/assets/12c64621-4e11-4a23-9efa-da5fa136db8b">

**Comment by johnmarktaylor91** [comment]
Can you clarify what you mean by random?

**Comment by johnmarktaylor91** [comment]
I see, so you want to be able to split the model anywhere you want. I am thinking of eventually adding functionality to causally intervene on the computational graph using torchlens, so I’ll keep this suggestion in mind!

**Comment by johnmarktaylor91** [comment]
In PyTorch, “buffers” are tensors that are associated with a model, but that are not trainable parameters. They can be used for any purpose, but in BatchNorm layers they’re used to store the running mean and standard deviation of tensors during the forward pass. TorchLens tracks these for completeness.

**Comment by johnmarktaylor91** [comment]
If you want me to debug it helps if you paste your code instead of a picture of the code :]

**Comment by johnmarktaylor91** [comment]
Figured it out. This is because the function executed is an "in-place" add (`iadd`, for example `x += 1`), so x1 is updated in-place. This is why y=x1 in this case.

**Comment by johnmarktaylor91** [comment]
Indeed, but the model uses the iadd function, so torchlens will necessarily reflect that.
